name: Build Android APK
on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest  # العودة للأسرع
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          # تحميل المكتبة المفقودة يدوياً لأنها حُذفت من النسخ الجديدة
          wget http://azure.archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.2-0ubuntu2_amd64.deb
          sudo apt install ./libtinfo5_6.2-0ubuntu2_amd64.deb
          sudo apt-get install -y libncurses5 libstdc++6 python3-pip
          pip3 install --user --upgrade buildozer

      - name: Build with Buildozer
        uses: artemSerebrennkov/buildozer-action@v1
        with:
          buildozer_version: stable

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: bin/*.apk
